name: Tolomet
options:
  bundleIdPrefix: com.akrog
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  Tolomet:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: TolometSimple
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akrog.tolomet
        INFOPLIST_FILE: TolometSimple/Info.plist
    dependencies:
      - framework: ../tolometShared/build/XCFrameworks/release/TolometShared.xcframework
